name: Build Ubuntu ARM RootFS

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-arm64-rootfs:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap jq
      - name: Run build script
        run: |
          chmod +x build_ubuntu.sh
          sudo ./build_ubuntu.sh
          - name: Upload tar.zst artifacts
            uses: actions/upload-artifact@v4
            with:
              name: tar-zst-artifacts
              path: "./*.tar.zst"
              if-no-files-found: warn
              compression-level: 5