name: LXC Build Ubuntu ARM RootFS

on:
  workflow_dispatch:

jobs:
  lxc-build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap lxc jq p7zip-full zstd curl wget ca-certificates \
            tar xz-utils gnupg dnsmasq-base uidmap

      - name: Run LXC build script
        run: |
          chmod +x build_ubuntu_lxc.sh
          sudo ./build_ubuntu_lxc.sh

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-rootfs-arm64
          path: |
            ./*.tar.zst
          if-no-files-found: error
          retention-days: 7
